#!/usr/bin/env bash

LAST_COMMIT_MESSAGE="$(git log -1 --pretty=format:%s)"
LAST_PROBLEM_NUMBER="${LAST_COMMIT_MESSAGE//[!0-9]/}"
PROPER_PROBLEM_NUMBER="$((LAST_PROBLEM_NUMBER + 1))"

git add .
git commit -m "Numero $PROPER_PROBLEM_NUMBER"

git push
